//! info.zig reports facts about the machine and about how the program was
//! built, as plain text or as JSON. It introduces the `builtin` module
//! (compile-time facts about the target), arena allocators, and two ways to
//! produce JSON: serializing a struct directly and writing fields one by one.

const std = @import("std");
// `builtin` is generated by the compiler for every build. It describes the
// target being compiled FOR, which matters when cross-compiling.
const builtin = @import("builtin");
const Io = std.Io;
const Allocator = std.mem.Allocator;
const EnvironMap = std.process.Environ.Map;

/// The output formats.
pub const Format = enum {
    text,
    json,
};

/// The collected facts. `std.json` can serialize a plain struct like this one
/// without any annotations; field names become the JSON keys.
pub const Info = struct {
    os: []const u8,
    arch: []const u8,
    zig_version: []const u8,
    build_mode: []const u8,
    hostname: []const u8,
    cpu_count: usize,
    total_memory_bytes: u64,
    current_directory: []const u8,
};

/// Collects system information and writes it to `out`. Pass an environment
/// map to include the environment variables, or null to leave them out.
pub fn run(io: Io, gpa: Allocator, out: *Io.Writer, format: Format, environ: ?*const EnvironMap) !void {
    // An arena hands out memory that is all released together by one
    // `deinit`. It suits short-lived work like this: allocate freely, never
    // free individually, and clean up once at the end.
    var arena_state: std.heap.ArenaAllocator = .init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const info = try collect(io, arena);
    const sorted_names: ?[][]const u8 = if (environ) |map| try sortedNames(arena, map) else null;

    switch (format) {
        .text => try writeText(out, info, environ, sorted_names),
        .json => try writeJson(out, info, environ, sorted_names),
    }
}

/// Gathers the facts. Strings that must be allocated come from `arena`.
pub fn collect(io: Io, arena: Allocator) !Info {
    return .{
        // `@tagName` turns an enum value into its name as a string.
        .os = @tagName(builtin.os.tag),
        .arch = @tagName(builtin.cpu.arch),
        .zig_version = builtin.zig_version_string,
        .build_mode = @tagName(builtin.mode),
        .hostname = try hostname(arena),
        .cpu_count = try std.Thread.getCpuCount(),
        .total_memory_bytes = try std.process.totalSystemMemory(),
        .current_directory = try std.process.currentPathAlloc(io, arena),
    };
}

fn hostname(arena: Allocator) ![]const u8 {
    // `builtin.os.tag` is known at compile time, so this `if` is decided
    // while compiling. The branch not taken is never analyzed, which is how
    // code that only exists on some platforms can share a file. This plays
    // the role of Go's build tags.
    if (builtin.os.tag == .windows) return "unknown";

    var buffer: [std.posix.HOST_NAME_MAX]u8 = undefined;
    const name = try std.posix.gethostname(&buffer);
    // `buffer` lives on this function's stack and vanishes on return, so the
    // name has to be copied somewhere that outlives the call.
    return arena.dupe(u8, name);
}

/// Returns the environment variable names in alphabetical order.
fn sortedNames(arena: Allocator, environ: *const EnvironMap) ![][]const u8 {
    // Sort a copy. Sorting `environ.keys()` in place would corrupt the map.
    const names = try arena.dupe([]const u8, environ.keys());
    std.mem.sort([]const u8, names, {}, nameLessThan);
    return names;
}

fn nameLessThan(context: void, a: []const u8, b: []const u8) bool {
    _ = context;
    return std.mem.lessThan(u8, a, b);
}

fn writeText(out: *Io.Writer, info: Info, environ: ?*const EnvironMap, sorted_names: ?[][]const u8) !void {
    try out.print("os:            {s}\n", .{info.os});
    try out.print("arch:          {s}\n", .{info.arch});
    try out.print("zig version:   {s}\n", .{info.zig_version});
    try out.print("build mode:    {s}\n", .{info.build_mode});
    try out.print("hostname:      {s}\n", .{info.hostname});
    try out.print("cpu count:     {d}\n", .{info.cpu_count});
    // `{Bi:.1}` formats a byte count with binary units, e.g. "48.0GiB".
    try out.print("total memory:  {Bi:.1}\n", .{info.total_memory_bytes});
    try out.print("current dir:   {s}\n", .{info.current_directory});

    // Unwrapping with `.?` asserts that an optional is not null. It is safe
    // here because `run` sets `sorted_names` whenever `environ` is set.
    if (environ) |map| {
        try out.writeAll("\nenvironment:\n");
        for (sorted_names.?) |name| {
            try out.print("  {s}={s}\n", .{ name, map.get(name).? });
        }
    }
}

fn writeJson(out: *Io.Writer, info: Info, environ: ?*const EnvironMap, sorted_names: ?[][]const u8) !void {
    // `std.json.Stringify` is a streaming JSON writer. `write` serializes any
    // value, while the begin/end calls let you build a document by hand.
    var stringify: std.json.Stringify = .{ .writer = out, .options = .{ .whitespace = .indent_2 } };
    try stringify.beginObject();

    try stringify.objectField("system");
    try stringify.write(info);

    if (environ) |map| {
        try stringify.objectField("environment");
        try stringify.beginObject();
        for (sorted_names.?) |name| {
            try stringify.objectField(name);
            try stringify.write(map.get(name).?);
        }
        try stringify.endObject();
    }

    try stringify.endObject();
    try out.writeByte('\n');
}

test "text output lists the system facts" {
    const gpa = std.testing.allocator;
    var output: Io.Writer.Allocating = .init(gpa);
    defer output.deinit();

    try run(std.testing.io, gpa, &output.writer, .text, null);
    try std.testing.expect(std.mem.indexOf(u8, output.written(), "zig version:   " ++ builtin.zig_version_string) != null);
    try std.testing.expect(std.mem.indexOf(u8, output.written(), "environment:") == null);
}

test "json output is valid and includes sorted environment variables" {
    const gpa = std.testing.allocator;
    var output: Io.Writer.Allocating = .init(gpa);
    defer output.deinit();

    var environ: EnvironMap = .init(gpa);
    defer environ.deinit();
    try environ.put("ZED", "last");
    try environ.put("ALPHA", "first");

    try run(std.testing.io, gpa, &output.writer, .json, &environ);

    const parsed = try std.json.parseFromSlice(std.json.Value, gpa, output.written(), .{});
    defer parsed.deinit();
    const system = parsed.value.object.get("system").?;
    try std.testing.expectEqualStrings(@tagName(builtin.os.tag), system.object.get("os").?.string);

    const alpha_position = std.mem.indexOf(u8, output.written(), "ALPHA").?;
    const zed_position = std.mem.indexOf(u8, output.written(), "ZED").?;
    try std.testing.expect(alpha_position < zed_position);
}
