//! main.zig is the entry point of the zigswiss executable. It sets up the shared
//! `cli.Context`, uses zig-clap to read the subcommand name, and dispatches to
//! the matching file in src/cmd. All real work happens in the "zigswiss" library
//! module under src/lib; see README.md for the recommended reading order.

const std = @import("std");
const builtin = @import("builtin");
const clap = @import("clap");
// Generated by build.zig with `b.addOptions()`. It carries the version string
// from build.zig.zon, and the repo URL, into the program at compile time.
const build_options = @import("build_options");
const cli = @import("cli.zig");
const Io = std.Io;

const cmd_archive = @import("cmd/archive.zig");
const cmd_bench = @import("cmd/bench.zig");
const cmd_codec = @import("cmd/codec.zig");
const cmd_compress = @import("cmd/compress.zig");
const cmd_crypt = @import("cmd/crypt.zig");
const cmd_fetch = @import("cmd/fetch.zig");
const cmd_generate = @import("cmd/generate.zig");
const cmd_hash = @import("cmd/hash.zig");
const cmd_info = @import("cmd/info.zig");
const cmd_json = @import("cmd/json.zig");
const cmd_jwt = @import("cmd/jwt.zig");
const cmd_net = @import("cmd/net.zig");
const cmd_time = @import("cmd/time.zig");
const cmd_transform = @import("cmd/transform.zig");

/// Every subcommand. zig-clap parses the first positional argument straight
/// into this enum, so an unknown command is rejected during parsing.
const Command = enum {
    archive,
    bench,
    compress,
    decode,
    decrypt,
    encode,
    encrypt,
    fetch,
    generate,
    hash,
    help,
    info,
    json,
    jwt,
    net,
    time,
    transform,
    version,
};

const main_params = clap.parseParamsComptime(
    \\-h, --help  Display this help and exit.
    \\<COMMAND>
    \\
);

const main_parsers = .{
    .COMMAND = clap.parsers.enumeration(Command),
};

const usage =
    \\zigswiss - a Swiss army knife CLI written in Zig
    \\
    \\Usage: zigswiss <command> [options]
    \\
    \\Commands:
    \\  archive    Create, list or extract .tar.gz archives
    \\  bench      Benchmark an HTTP endpoint with concurrent requests
    \\  compress   Compress (gzip, zlib) or decompress (gzip, zlib, zstd, xz)
    \\  decode     Decode base64, base64url, hex or url text
    \\  decrypt    Decrypt a file made by the encrypt command
    \\  encode     Encode data as base64, base64url, hex or url text
    \\  encrypt    Encrypt a file with AES-256-GCM and a password
    \\  fetch      Make an HTTP(S) request
    \\  generate   Generate passwords, tokens or UUIDs
    \\  hash       Hash files or stdin, optionally as an HMAC
    \\  info       Show system and build information
    \\  json       Pretty-print, compact, validate or query JSON
    \\  jwt        Decode a JSON Web Token (no signature verification)
    \\  net        Check whether TCP ports are open
    \\  time       Convert between epoch seconds and ISO 8601 timestamps
    \\  transform  Transform text (case, sort, uniq, count, replace, freq)
    \\  version    Show version information
    \\
    \\Run 'zigswiss <command> --help' for the options of a command.
    \\
;

/// Zig 0.16 passes `std.process.Init` to main. It bundles what a program
/// needs from its environment: arguments, environment variables, an allocator
/// and the `Io` implementation. The `!void` return type means main may fail
/// with any error; the error set is inferred by the compiler.
pub fn main(init: std.process.Init) !void {
    // Writers own no memory. This buffer collects output until it is full or
    // until `flush` is called, which keeps the number of system calls low.
    //
    // `writerStreaming` matters. The plain `writer` works "positionally": it
    // writes at explicit file offsets starting from 0. That is right for a
    // file we just created, but stdout may be a file the shell opened in the
    // middle (`>> log.txt`), and positional writes would overwrite its start.
    // Streaming mode writes wherever the file's current position is.
    var stdout_buffer: [4096]u8 = undefined;
    var stdout_writer = Io.File.stdout().writerStreaming(init.io, &stdout_buffer);
    const out = &stdout_writer.interface;

    var args = try init.minimal.args.iterateAllocator(init.gpa);
    defer args.deinit();
    // Skip the program name.
    _ = args.next();

    var ctx: cli.Context = .{
        .io = init.io,
        .gpa = init.gpa,
        .out = out,
        .args = &args,
        .environ_map = init.environ_map,
    };

    const succeeded = runCommand(&ctx);
    // Flush whatever the command managed to write, even if it failed later.
    try out.flush();
    if (!succeeded) std.process.exit(1);
}

/// Parses the subcommand name, runs it and reports failure. Returns true on
/// success. Kept separate from `main` so that every `defer` in here has run
/// before `main` calls `std.process.exit`, which does not run deferred code.
fn runCommand(ctx: *cli.Context) bool {
    // `terminating_positional = 0` stops parsing right after the subcommand
    // name. The rest of the arguments stay in `ctx.args` for the subcommand.
    var diagnostic: clap.Diagnostic = .{};
    var res = clap.parseEx(clap.Help, &main_params, main_parsers, ctx.args, .{
        .diagnostic = &diagnostic,
        .allocator = ctx.gpa,
        .terminating_positional = 0,
    }) catch |err| {
        cli.reportParseError(ctx.io, diagnostic, err);
        std.log.err("run 'zigswiss help' for the list of commands", .{});
        return false;
    };
    defer res.deinit();

    // A missing subcommand, or --help, prints the usage text.
    const command = res.positionals[0] orelse Command.help;
    if (res.args.help != 0 or command == .help) {
        ctx.out.writeAll(usage) catch return false;
        return true;
    }

    dispatch(ctx, command) catch |err| {
        // `std.log` writes to stderr with a severity prefix: "error: ...".
        std.log.err("{s}: {s}", .{ @tagName(command), @errorName(err) });
        return false;
    };
    return true;
}

/// The switch must name every member of `Command`. Add a command to the enum
/// and the compiler points here until it is handled.
fn dispatch(ctx: *cli.Context, command: Command) !void {
    switch (command) {
        .archive => try cmd_archive.run(ctx),
        .bench => try cmd_bench.run(ctx),
        .compress => try cmd_compress.run(ctx),
        .decode => try cmd_codec.runDecode(ctx),
        .decrypt => try cmd_crypt.runDecrypt(ctx),
        .encode => try cmd_codec.runEncode(ctx),
        .encrypt => try cmd_crypt.runEncrypt(ctx),
        .fetch => try cmd_fetch.run(ctx),
        .generate => try cmd_generate.run(ctx),
        .hash => try cmd_hash.run(ctx),
        .help => try ctx.out.writeAll(usage),
        .info => try cmd_info.run(ctx),
        .json => try cmd_json.run(ctx),
        .jwt => try cmd_jwt.run(ctx),
        .net => try cmd_net.run(ctx),
        .time => try cmd_time.run(ctx),
        .transform => try cmd_transform.run(ctx),
        .version => try ctx.out.print("zigswiss {s} (zig {s}, {s}, {s}-{s})\n{s}\n", .{
            build_options.version,
            builtin.zig_version_string,
            @tagName(builtin.mode),
            @tagName(builtin.cpu.arch),
            @tagName(builtin.os.tag),
            build_options.repo_url,
        }),
    }
}
